server:
  port: 8761

spring:
  application:
    name: service-registry
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
logging:
  file:
    name:  C:\workspace\logs\service-regitry.log
   # path: C:\JavaTeaching\Microservice\latestMicroservices\logs
  logback:
    rollingpolicy:
      max-file-size: 10MB      