
#Server Port
server:
  port: 8081
#Name of the application 
spring:
  application:
    name: employee-service
   #Database Configurations
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_management
    username: root
    password: Admin@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#Eureka Server Configurations
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  file:
    name:  C:\workspace\logs\employee-service.log
