server:
  port: 8085
  
spring:  
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/departments/**
        - id: USER-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
#Eureka Server Configurations
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
   
#Logging service logs   
logging:
  file:
    name:  C:\workspace\logs\api-gateway.log
