#Server Port
server:
  port: 8082
#Name of the application 
spring:
   #Database Configurations
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: Admin@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#Eureka Server Configurations
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  #file:
    #name:  C:\workspace\logs\user-service.log
  level:
    org:
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            bind: trace
            
#Circuit Breaker Properties

management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      
      
#debug = true

#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#logging.level.org.hibernate.type.descriptor.sql=TRACE   
#Can be fined at package and class level
#logging.level.org.springframework.web=INFO
#logging.level.org.hibernate=ERROR
#logging.level.com.user.crud.controller= DEBUG
#logging.pattern.console= %d [%level] %c {1.} [%t] %m%n
#logging.file.path = C:/workspace/logs/users.log
#logging.pattern.file=%d [%level] %c {1.} [%t] %m%n





#logging.file = relativepath/to/logfile.log     //relative path with filename
#logging.file = /fullpath/to/logfile.log        //full path with filename
# SQL statements and parameters
#log4j.logger.org.hibernate.SQL=debug
#log4j.logger.org.hibernate.type.descriptor.sql=trace
#spring.jpa.properties.hibernate.format_sql=true
